// Auto-generated by Aptly — do not edit manually
export const site = {
  companyName: "DevTest - Aptly01 (RV)",
  tagline: "We Ride Hard For Yo Property",
  description: "We handle that shit so you ain't gotta stress. Stack yo bread while we hold it down.",
  phone: "",
  email: "",
  address: "",
  colors: {
    primary: "#2f6df6",
    primaryDark: '#1a56db',
    bg: '#f7f8fb',
    surface: '#ffffff',
    ink: '#161b26',
    muted: '#7a8395',
  },
  nav: [
    { label: 'Services', href: '#services' },
    { label: 'About', href: '#about' },
    { label: 'Testimonials', href: '#testimonials' },
    { label: 'Contact', href: '#contact' },
  ],
  hero: {
    headline: 'We Hold Yo Property Down, No Cap',
    subheadline: "Stack yo bread and let us handle all that landlord shit. We got you, fam.",
    cta: 'Get Yo Free Consultation',
    ctaHref: '#contact',
  },
  services: [
    { icon: '🏠', title: 'Leasing & Marketing', description: 'We put yo unit on blast wit professional pics, syndicated listings, and we screen them tenants hard so no cap artists slide through.' },
    { icon: '🔧', title: 'Maintenance & Repairs', description: '24/7 emergency response, no ghostin. We got a squad of trusted vendors ready to pull up and fix that shit.' },
    { icon: '💰', title: 'Rent Collection', description: 'We collect that paper automatically, hit yo account with the bread, and send you them monthly statements so you always know what\'s good.' },
    { icon: '📊', title: 'Financial Reporting', description: 'Real-time owner portal wit all yo income, expenses, and transaction history. Know where every dollar at, straight up.' },
    { icon: '⚖️', title: 'Legal Compliance', description: 'We stay up on all them landlord-tenant laws so you don\'t catch a case. Lease enforcement and eviction management, we handle it all.' },
    { icon: '🤝', title: 'Tenant Relations', description: 'We keep it real wit tenants — responsive communication, move-in and move-out inspections so nobody try to play us.' },
  ],
  stats: [
    { value: '500+', label: 'Properties Held Down' },
    { value: '10+', label: 'Years In The Game' },
    { value: '98%', label: 'Occupancy Rate' },
    { value: '4.9★', label: 'Owner Rating' },
  ],
  about: {
    headline: 'Local Hustlers. Owner Focused. No Snitchin.',
    body: "We ain't some corporate suit operation. We local, we licensed, and we ride hard for every owner on our roster. You stack the properties, we handle all that other noise. Period.",
    points: [
      'Licensed and holdin it down wit full fiduciary responsibility',
      'Dedicated owner portal wit real-time reporting — stay in the know',
      'Fast turnaround on maintenance so tenants ain\'t beefin',
      'No hidden fees — flat rate only, we keep it a hunnid',
    ],
  },
  testimonials: [
    { quote: 'These folks the realest property managers I ever worked wit. They handle everything and I just collect my bag.', author: 'Michael T.', detail: 'Owner of 4 properties' },
    { quote: 'They filled my vacancy in 11 days no cap. And they actually pick up the phone, that\'s rare fr fr.', author: 'Sarah K.', detail: 'Duplex owner' },
    { quote: 'Finally a property manager that don\'t ghost you. These guys stay on point and keep the bread flowin.', author: 'James R.', detail: 'Commercial property investor' },
  ],
  contact: {
    headline: 'You Ready To Get This Bread?',
    subheadline: 'Hit us up and get a free rental analysis and management proposal within 24 hours. We don\'t play.',
  },
  seo: {
    title: "DevTest - Aptly01 (RV) | Professional Property Management",
    description: "We handle that shit so you ain't gotta stress. Stack yo bread while we hold it down.",
    ogImage: '/images/og.jpg',
  },
  social: { facebook: '', instagram: '', linkedin: '' },
};
